//import { set } from 'core-js/core/dict'
import React, { useState } from 'react'
import key from './key.json' //key.json must be in the components folder for this to function properly
require('dotenv').config();

// console.log(process.env.NODE_ENV)
// console.log(process.env)

const { GoogleSpreadsheet } = require('google-spreadsheet');
// Initialize the sheet - doc ID is the long id in the sheets URL
const doc = new GoogleSpreadsheet('1-e1YndrEsvlwQ13tUJii35fTR5PillBqZRYIX7JMQek');

const client_email = process.env.REACT_APP_CLIENT_EMAIL
const private_key = process.env.REACT_APP_PRIVATE_KEY

console.log(`Client EMAIL TYPE: ${typeof client_email}`)

// AUTH if NODE_ENV production ie. NEtlify must have .env vars CLIENT_EMAIL PRIVATE KEY values are from gcloud service account creds
if(process.env.NODE_ENV === "production"){
  (async function() {
    console.log(`In Production - ${process.env.REACT_APP_CLIENT_EMAIL}`)
    await doc.useServiceAccountAuth({
      // env var values are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      client_email:client_email,
      private_key:private_key
    });
  }());
} else {
  (async function() {
    console.log('In Dev mode')
    await doc.useServiceAccountAuth({
      //pulled from a key.json for local dev
      // see "Authentication" section in docs for more info
      client_email:key.client_email,
      private_key:key.private_key
    });
  }());
}



const SizeForm = (props) => {

  const [name, setName] = useState('')
  const [height, setHeight] = useState('')
  const [inseam, setInseam] = useState('')
  const [torsoLength, setTorsoLength] = useState('')
  const [email,setEmail] = useState('')
    

  const nameFieldHandler = (e) => {
    e.preventDefault()
    setName(e.target.value)
  }

  const heightFieldHandler = (e) => {
    e.preventDefault()
    setHeight(e.target.value)
  }

  const inseamFieldHanlder = (e) => {
    e.preventDefault()
    setInseam(e.target.value)
  }

  const torsoLengthFieldHandler = (e) => {
    e.preventDefault()
    setTorsoLength(e.target.value)
  }

  
  const emailFieldHandler = (e) => {
    e.preventDefault();
    setEmail(e.target.value);
  }

  const handleForm = (e) => {
    e.preventDefault()
    
    console.log('form submitted')
    
    const user = {
      name: name,
      email: email,
      height: height,
      inseam: inseam,
      torsoLength: torsoLength,
      metricsFlag: false,
      riderFit: {saddleHeight:'',
        saddleStack:'',
        stackHeight:['',''],
        reach:''
      },
      
      setRiderFit: function(){
        
        const saddleHeight = this.inseam *.883 ; 
        const saddleStack = saddleHeight*Math.cos(.296706)
        const stemHeightRange = [Math.floor(.2*this.inseam - 11), Math.floor(.2*this.inseam - 13)]

        const stackHeight = [Math.floor(saddleStack-stemHeightRange[0]),Math.floor(saddleStack-stemHeightRange[1])] ;
        
        //const reach = (2*this.inseam-this.torsoLength+29)/3 ; //R=(2inseam-torso+29)/3 or r = .09090909091*(3H+1.5T-115.5) Font Should be Obvia regular
        
        const reach = .090909091*(3*this.height+1.5*this.torsoLength-105.5); // possibly a better equation
        
        this.riderFit.saddleHeight = saddleHeight ;
        this.riderFit.saddleStack = saddleStack ;
        if(stackHeight[0] !== 11){
        this.riderFit.stackHeight = stackHeight ;} //this is hacky, better solution must be found
        this.riderFit.reach = [reach-1,reach+1] ;
      }

    }

    

    user.setRiderFit();

    (async function() {
      await doc.loadInfo(); // loads document properties and worksheets
      console.log(doc.title); // logs doc title for testing purposes
      const sheet = doc.sheetsByIndex[0]; // creates sheet var
      console.log(sheet.title) // logs sheet name for testing
      await sheet.addRow({ Name: user.name, SaddleHeight: user.riderFit.saddleHeight, ReachMin: user.riderFit.reach[0], ReachMax: user.riderFit.reach[1], StackHeight: user.riderFit.stackHeight[0]+1, Height: user.height, Torso: user.torsoLength, Email: user.email }); //modifies sheet with user input
    }());

    //const savedInfo = {name: user.name, height: user.height, inseam: user.inseam, torsoLength: user.torsoLength, saddleHeight: user.riderFit.saddleHeight,
      //stackHeightMin: user.riderFit.stackHeight[0], stackHeightMax: user.riderFit.stackHeight//[1], reachMin: user.riderFit.reach[0], reachMax: user.riderFit.reach[1]
    //}

    props.onFormSubmit(user)
    // alert(`${user.name} ${user.height} ${user.inseam} submitted`)
    
    //api post request to save data in a google form
    

    //reset form
    setName('')
    setHeight('')
    setInseam('')
    setTorsoLength('')
    setEmail('')
    
  }


  return (
    <form onSubmit={handleForm} className={`flex flex-col ${props.classes}`}>
      <input type="text" placeholder="Name" value={name} onChange={nameFieldHandler} className="border-2 rounded-md my-2 p-2" />
      <input type="text" placeholder="Email" value={email} onChange={emailFieldHandler} className="border-2 rounded-md my-2 p-2" />
      <input type="text" placeholder="Height (cm)" value={height} onChange={heightFieldHandler} className="border-2 rounded-md my-2 p-2" />
      <input type="text" placeholder="Inseam (cm)" value={inseam} onChange={inseamFieldHanlder} className="border-2 rounded-md my-2 p-2" />
      <input type="text" placeholder="Torso Length (cm)" value={torsoLength} onChange={torsoLengthFieldHandler} className="border-2 rounded-md my-2 p-2" />
      <input type="submit" className="bg-blue-500 text-white p-2 my-2 rounded-md hover:bg-blue-300 hover:text-blue-800" />
    </form>
  )
}

export default SizeForm
